server:
  port: 8082
  servlet:
    context-path: /auth
spring:
  application:
    name: cf-ucenter-auth
  redis:
    host: 127.0.0.1
    port: 6379
    #    password: redis密码
    database: 0
    jedis:
      pool:
        maxActive: 20
        maxIdle: 20
        minIdle: 10
        maxWait: -1
  datasource:
    name: caifeng
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://127.0.0.1:3306/caifeng?characterEncoding=utf-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    maxActive: 32
    druid:
      url: ${MYSQL_URL:jdbc:mysql://127.0.0.1:3306/caifeng?characterEncoding=utf-8&useSSL=false}
      username: root
      password: 123456
      driverClassName: com.mysql.jdbc.Driver
      initialSize: 5  #初始建立连接数量
      minIdle: 5  #最小连接数量
      maxActive: 20 #最大连接数量
      maxWait: 10000  #获取连接最大等待时间，毫秒
      testOnBorrow: true #申请连接时检测连接是否有效
      testOnReturn: false #归还连接时检测连接是否有效
      timeBetweenEvictionRunsMillis: 60000 #配置间隔检测连接是否有效的时间（单位是毫秒）
      minEvictableIdleTimeMillis: 300000  #连接在连接池的最小生存时间（毫秒）
auth:
  tokenValiditySeconds: 1200  #redis的token的过期时间(暂时不用)
  clientId: yangzhichao
  clientSecret: 123qwe
  cookieDomain: xuecheng.com
  cookieMaxAge: -1
encrypt:
  key-store:
    location: classpath:/cfzh.keystore
#    location: classpath:/cfzh.jks
#    location: classpath:/xc.keystore
    secret: 123456
    alias: cfzh
    password: 123456

dubbo:
  scan:
    base-packages: com.cf.ucenter.auth.service
  application:
    name: ${spring.application.name}
  protocol:
    name: dubbo
    port: 20883
  registry:
    address: zookeeper://127.0.0.1:2181
  provider:
    filter: -exception
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl




